name: "🐞 Bug Report"
description: "Something isn't working as expected."
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug!  Please ensure there is no existing issue that matches before posting.
  - type: textarea
    id: summary
    attributes:
      label: "🔍 Summary"
      description: "A clear and concise description of what the bug is."
      placeholder: "When I run `python pipeline.py`, I get ..."
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "🚶‍♂️ Steps to Reproduce"
      description: "Exact steps or code to reproduce the behavior."
      placeholder: "1. Clone repo\n2. Create env ...\n3. Run ..."
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "✅ Expected Behavior"
      description: "What did you expect to happen?"
      required: true
  - type: textarea
    id: actual
    attributes:
      label: "❌ Actual Behavior"
      description: "What actually happened instead? Include full error trace if possible."
      required: true
  - type: input
    id: version
    attributes:
      label: "📦 Version"
      description: "Commit hash or release tag where this bug is observed."
      required: false
  - type: textarea
    id: env
    attributes:
      label: "💻 Environment"
      description: "OS, Python version, Docker/no‑Docker, GPU/CPU, etc."
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre‑Issue Checklist"
      options:
        - label: "I have searched existing issues and discussions."
          required: true
        - label: "I have read the documentation / FAQ."
          required: false

