name: "ReefLit AI CI"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  # Nightly cron-job keeps the living meta-analysis fresh
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC daily
  workflow_dispatch: 

# ---------------------------------------------------------------------- #
# 1) Basic lint / unit-test stage
# ---------------------------------------------------------------------- #
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install core dev deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run unit tests (if any)
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests yet - skipping."
          fi

# ---------------------------------------------------------------------- #
# 2) Nightly end-to-end pipeline in Docker
# ---------------------------------------------------------------------- #
  nightly-pipeline:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'          # ← only cron triggers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build pipeline Docker image
        run: docker build -f Dockerfile.pipeline -t reeflit-pipeline .

      - name: Run pipeline container (fetch → label → index)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/data:/app/data \
            -v ${{ github.workspace }}/index:/app/index \
            reeflit-pipeline

      - name: Upload nightly artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reeflit-data
          path: |
            data/coral_corpus.jsonl
            data/corpus_labeled.jsonl
            index/reeflit.faiss
            index/metadata.pkl
