name: "ReefLit AI CI"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  # Nightly run to keep the living meta-analysis fresh
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC (~midnight US ET)

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Minimal core libs for pipeline skeleton
          pip install spacy==3.* sentence-transformers==2.* faiss-cpu==1.* pytest

      - name: Run unit tests (if any)
        run: |
          if [ -d tests ]; then pytest -q; else echo "No tests directory yet – skipping."; fi

      - name: Build FAISS index (nightly only)
        if: github.event_name == 'schedule'
        run: python src/build_index.py --input data/corpus_labeled.jsonl


  nightly-pipeline:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pipeline dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run ingest script
        run: |
          python scripts/ingest.py || echo "Ingest script placeholder – implement later."

